# Generated by Django 4.2 on 2025-07-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
